### ISSUE TITLE
fix memory leak: remove forgetmechunk

### ISSUE THREAD

**Issue by WilliamAnimate** [XanderFromFortnite/WonderfullyOptimized#2]
forgetmechunk prevents something something unloads on the client, aka doesn't free memory.

adding a mod like phosphor or starlight (faster) will partially mitigate the problem

# **however**
i have no clue if those mods are for singleplayer or works for multiplayer too so like its up to you

**Comment by XanderFromFortnite** [comment]
ok thanks, noted

**Comment by WilliamAnimate** [comment]
![image](https://user-images.githubusercontent.com/75321465/233521613-4a375402-4a8a-46ff-96cf-b04c2ba56073.png)
update: on v1.20 it is 100% fixed so the memory leak wont plague newer versions

**Comment by XanderFromFortnite** [comment]
Oh ok, I was gonna remove the mod next update but now since the problem is fixed, I'll just leave it, thanks for telling me.
